Rails:
  Enabled: false

Metrics/LineLength:
  Max: 140

Style/Documentation:
  Enabled: false

Style/NonNilCheck:
  IncludeSemanticChanges: true

Style/FileName:
  Exclude:
    - 'Gemfile.local.rb'
    - 'Gemfile.local.example.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*

AllCops:
  TargetRubyVersion: 2.6.2
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'bin/**/*'
